(TeX-add-style-hook "main"
 (lambda ()
    (TeX-run-style-hooks
     "natbib"
     "super"
     "hyperref"
     "flexisym"
     "subscript"
     "siunitx"
     "algorithm"
     "algorithmic"
     "cite"
     "graphicx"
     ""
     "thesis-tap"
     "introduction"
     "Background"
     "methods"
     "sequencing"
     "assembly"
     "Expression"
     "discussion"
     "conclusions"
     "bibtex")))

